### GET request to read all users
GET http://localhost:3000/api/v2/users


### POST request to create new users
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "เชร็ค",
    "email": "SHrek@example.com",
    "password": "shrek1234"
}

### DELETE request
DELETE http://localhost:3000/api/v1/users/4
