### GET request to read all users
GET http://localhost:3000/api/v1/users


### POST request to create new users
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "name": "Mom",
    "email": "mom@example.com"
}

### DELETE request
DELETE http://localhost:3000/api/v1/users/4
